apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deploy
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: backend-deploy
    spec:
      volumes:
      - name: backend-vol
        persistentVolumeClaim:
          claimName: backend-pvc
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: backend-vol
          mountPath: /data

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
reclaimPolicy: Delete # default value is Delete
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standred

---



