apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - patch
  - delete
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - patch
  - delete
  - get
  - list
