apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - patch
  - delete
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - patch
  - delete
  - get
  - list
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ajay
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: dev
---

