apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  terminationGracePeriodSeconds: 15
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
