apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-pod
  name: busybox-pod
spec:
  terminationGracePeriodSeconds: 15
  restartPolicy: Always
  containers:
  - image: busybox
    name: busybox-pod
    imagePullPolicy: IfNotPresent
    command:
    - "sh"
    - "-c"
    - "touch /tmp/healthz && sleep infinity"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
    readinessProbe:
      exec:
        command: ["sh", "-c", "cat /tmp/healthz"]
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 2
      successThreshold: 2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

