apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-probe-demo
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 10
  containers:
  - name: liveness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 2

