apiVersion: v1
kind: Pod
metadata:
  labels:
    run: static-check
  name: static-check
spec:
  containers:
  - image: busybox
    name: static-check
    resources: {}
    command:
    - "sh"
    - "-c"
    - "sleep 1000"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
