apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: my-deployment
    env: test
  name: my-deployment
spec:
  replicas: 3
  selector:
    app: my-deployment
    env: test
  template:
    metadata:
      labels:
        app: my-deployment
        env: test
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        resources: {}

