apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:33081
  name: kind-my-first-cluster
contexts:
- context:
    cluster: kind-my-first-cluster
    namespace: default
    user: kind-my-first-cluster
  name: kind-my-first-cluster
current-context: kind-my-first-cluster
kind: Config
users:
- name: kind-my-first-cluster
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
